<?php $this->headScript()->prependFile((false !== @file_get_contents(RCMS_Object_QuickConfig_QuickConfig::G_JQUI_HOSTED_URL)) ? RCMS_Object_QuickConfig_QuickConfig::G_JQUI_HOSTED_URL : $this->websiteUrl . 'system/js/jquery/jquery-ui.js'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/jquery-ui-theme/jquery-ui-1.8.5.custom.css','screen'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'plugins/buyerarea/system/buyerarea.css','screen'); ?>
<script type="text/javascript">
    $(document).ready(function(){
        $('#buyerarea_usermenu a')
            .button()
            .click(function(event){
                event.preventDefault();
                tb_show('', $(this).attr('href')+'?TB_iframe=true&height=600&width=800','')
            });
    });
</script>
<div id="buyerarea_main">
    <div id="buyerarea_usermenu">
        <p style="margin-bottom: 10px; font-weight: bold; text-align: center">Manage your buyer account:</p>
        <a title="My account details" href="http://www.google.com.ua/" >My account details</a>
        <a title="My history" href="http://www.youtube.com/" >My history</a>

    </div>
</div>