<?php $this->headLink()->prependStylesheet($this->websiteUrl . 'plugins/buyerarea/system/buyerarea.css','screen'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/jquery-ui-theme/jquery-ui-1.8.5.custom.css','screen'); ?>
<?php echo $this->headLink(); ?>
<?php $this->headScript()->prependFile((false !== @file_get_contents(RCMS_Object_QuickConfig_QuickConfig::G_JQ_HOSTED_URL)) ? RCMS_Object_QuickConfig_QuickConfig::G_JQ_HOSTED_URL : $this->websiteUrl . 'system/js/jquery/jquery.js'); ?>
<?php $this->headScript()->prependFile((false !== @file_get_contents(RCMS_Object_QuickConfig_QuickConfig::G_JQUI_HOSTED_URL)) ? RCMS_Object_QuickConfig_QuickConfig::G_JQUI_HOSTED_URL : $this->websiteUrl . 'system/js/jquery/jquery-ui.js'); ?>
<?php echo $this->headScript(); ?>
<div id="buyerarea_main">
    <div id="buyerarea_userinfo">
        <div id="buyerarea_caption">
            Welcome in Buyer Area!
        </div>

        <div id="buyerarea_billingdata">
            <table>
                <thead>
                    <th colspan="2">Billing Address:</th>
                </thead>
                <tbody>
                    <tr><td>Firstname:</td><td><?php echo $this->billingAddress['firstname']; ?></td></tr>
                    <tr><td>Lastname:</td><td><?php echo $this->billingAddress['lastname']; ?></td></tr>
                    <tr><td>Company:</td><td><?php echo $this->billingAddress['company']; ?></td></tr>
                    <tr><td>Email:</td><td><?php echo $this->billingAddress['email']; ?></td></tr>
                    <tr><td>Phone:</td><td><?php echo $this->billingAddress['phone']; ?></td></tr>
                    <tr><td>Country:</td><td><?php echo $this->billingAddress['country']; ?></td></tr>
                    <tr><td>City:</td><td><?php echo $this->billingAddress['city']; ?></td></tr>
                    <tr><td>State:</td><td><?php echo $this->billingAddress['state']; ?></td></tr>
                    <tr><td>Zip:</td><td><?php echo $this->billingAddress['zip']; ?></td></tr>
                </tbody>
            </table>
        </div>

        <div id="buyerarea_shippingdata">
            <table>
                <thead>
                    <th colspan="2">Shipping Address:</th>
                </thead>
                <tbody>
                    <tr><td>Firstname:</td><td><?php echo $this->shippingAddress['firstname']; ?></td></tr>
                    <tr><td>Lastname:</td><td><?php echo $this->shippingAddress['lastname']; ?></td></tr>
                    <tr><td>Company:</td><td><?php echo $this->shippingAddress['company']; ?></td></tr>
                    <tr><td>Email:</td><td><?php echo $this->shippingAddress['email']; ?></td></tr>
                    <tr><td>Phone:</td><td><?php echo $this->shippingAddress['phone']; ?></td></tr>
                    <tr><td>Country:</td><td><?php echo $this->shippingAddress['country']; ?></td></tr>
                    <tr><td>City:</td><td><?php echo $this->shippingAddress['city']; ?></td></tr>
                    <tr><td>State:</td><td><?php echo $this->shippingAddress['state']; ?></td></tr>
                    <tr><td>Zip:</td><td><?php echo $this->shippingAddress['zip']; ?></td></tr>
                </tbody>
            </table>
        </div>
      
    </div>
</div>