<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <?php $this->headScript()->appendFile((false !== @file_get_contents(RCMS_Object_QuickConfig_QuickConfig::G_JQ_HOSTED_URL)) ? RCMS_Object_QuickConfig_QuickConfig::G_JQ_HOSTED_URL : $this->websiteUrl . 'system/js/jquery/jquery.js'); ?>
        <?php $this->headScript()->appendFile((false !== @file_get_contents(RCMS_Object_QuickConfig_QuickConfig::G_JQUI_HOSTED_URL)) ? RCMS_Object_QuickConfig_QuickConfig::G_JQUI_HOSTED_URL : $this->websiteUrl . 'system/js/jquery/jquery-ui.js'); ?>
        <?php $this->headScript()->appendFile($this->websiteUrl . 'system/js/jquery/plugins/DataTables/jquery.dataTables.min.js'); ?>
        <?php echo $this->headScript(); ?>
        <?php $this->headLink()->prependStylesheet($this->websiteUrl . 'plugins/buyerarea/css/buyerarea.css','screen'); ?>
        <?php $this->headLink()->appendStylesheet($this->websiteUrl . 'plugins/buyerarea/css/jquery-ui/jquery-ui-1.8.6.custom.css');?>
        <?php echo $this->headLink(); ?>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title><?php echo $this->translate('Buyer Area'); ?> :: <?php echo $this->translate('Manage client accounts'); ?></title>
        <script type="text/javascript">
            var buyersTable;
            $(document).ready(function(){
                $( "div:ui-dialog" ).dialog( "destroy" );
                
                $('#dialog-userinfo').dialog({
                    autoOpen: false,
                    resizable: false,
					draggable: true,
                    width: 750,
                    height: 550,
                    modal: false,
                    buttons: {
                        "<?php echo $this->translate('Save'); ?>": function(){
							var info = new Object;
							$('#userinfo-form :input').each(function(){
								info[ $(this).attr("name") ] = $(this).val() ;
							});
							
							$.ajax({
								url: '<?php echo $this->websiteUrl;?>plugin/buyerarea?run=updclient',
								type: 'POST',
								dataType: 'json',
								data: {info: info},
								success: function( responce ) {
									if (responce.done) {
										var widget = $('<div class="ui-widget" />').css({'width': '50%'});
										$('<div class="ui-state-highlight ui-corner-all"></div>')
										.css({'padding': '2px 4px'})
										.prepend( 
											$('<p>')
											.text('<?php echo $this->translate('User updated'); ?>')
											.prepend('<span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-info"/>')
										).appendTo(widget)
										$(widget).appendTo($('#dialog-userinfo').parent().children(':last') );
										window.setTimeout(function(){ $(widget).remove() }, '5000');
									}
								}
							})
                        },
                        "<?php echo $this->translate('Cancel'); ?>": function(){
                            $(this).dialog( "close" );
                        }
                    },
					open: function(){
						var url = '<?php echo $this->websiteUrl;?>plugin/buyerarea?run=getbuyerpayments&id='+$('#dialog-userinfo-userid').val();
						$('#dialog-userinfo-history-table').dataTable({
							//"bDestroy": true,
							"bProcessing": true,
							"sAjaxSource": url,
							"bJQueryUI": true,
							"bAutoWidth": false,
							"bPaginate": false,
							"sScrollY": "140px",
							"aoColumnDefs": [
								{ "bSortable": false, "aTargets": [ -1 ] }
							],
							"fnInitComplete": function() {
								$(this).find('.user-toolbar-button').button();
								
							}
						});

					},
                    beforeClose: function(event, ui) { 
						$(this).find('#userinfo-form input').val('');
						$(this).find('select[name$="state"]').html('');
						$('#dialog-userinfo-history-table').dataTable().fnDestroy();
					}
                });

                $('.button-info').button({icons: {primary: "ui-icon-person"}}).live('click', function(){
                    var id = $(this).closest('tr').find('td.buyer-id').text();
                    var userdata = {};
                    
                    $.ajax({
                        async: false,
                        url: '<?php echo $this->websiteUrl;?>plugin/buyerarea?run=getbuyerinfo',
                        type: 'POST',
                        data: {id: id},
                        dataType: 'json',
                        success: function(data){
                            if (data.done !== false){
                                var billAdr = data.billing_address;
                                if (billAdr !== null){
                                    if (billAdr.country == 'US' || billAdr.country == 'CA') {
                                        $('#billing-address-state').html(loadStates(billAdr.country))
                                    }
                                    for (i in billAdr) {
                                        $('#userinfo-form').find(':input[name="billing-address-'+i+'"]').val(billAdr[i]);
                                    }
                                }

                                var shippAdr = data.shipping_address;
                                if (shippAdr !== null){
                                    for (j in shippAdr){
                                        $('#userinfo-form').find(':input[name="shipping-address-'+j+'"]').val(shippAdr[j]);
                                    }
                                    if (null !== shippAdr.state){
                                        $('#shipping-address-state').html(loadStates(shippAdr.country)).val(shippAdr.state);
                                    }
                                }
								$('#dialog-userinfo-userid').val(id);
                                $('#dialog-userinfo').dialog( "open" );
                            }
                        }
                    });
                });

				$('.button-invoice').live('click',function(){
					var url = $(this).attr('link');
					$('#dialog-invoice:ui-dialog').dialog('destroy');
					$('#dialog-invoice').dialog({
						modal: true,
						resizable: false,
						draggable: false,
						height: 190,
						width: 350,
						zIndex: 2000,
						title: 'Create invoice',
						buttons: [
							{
								text: "OK",
								click: function(){									
									var invoiceId		= $('#invoice_id').val();
									var paymentMethod	= $('#payment_method').val();
									var shippingTaxRate	= $('#shipping_tax_rate').val();

									paymentMethod = paymentMethod.replace(/^\s+/, '');
									paymentMethod = paymentMethod.replace(/\s+$/, '');

									if (/^\d+$/.test(invoiceId) === false){
										$('#invoice_id').focus().prev('label').animate({color: 'red'}, 800).animate({color: 'black'}, 600);
										return;
									} else {
										url = url.replace('{cid}', invoiceId);
									}
									
									url = url.replace('{pm}', paymentMethod);

									if (shippingTaxRate.length && isNaN(shippingTaxRate)){
										$('#shipping_tax_rate').focus().prev('label').animate({color: 'red'}, 800).animate({color: 'black'}, 600);
										return;
									} else {
										url += '/shippingtaxrate/'+parseFloat(shippingTaxRate)+'/';
									}
									$(this).dialog("destroy");
									if (window !== top) {
										top.location.href = url;
									} else {
										window.location.href = url;
									}
								}
							}
						],
						open: function(event, ui) {
							var zIndex = parseInt($('#dialog-invoice').dialog( "option", "zIndex" )) - 1;
							$('#dialog-invoice:ui-dialog')
								.parent()
								.prev('div.ui-widget-overlay')
								.css({zIndex: zIndex });
						},
						close: function(event, ui) {
							$(this).dialog("destroy");
						}
					});
				});
				$('.button-quote').live('click',function(){
					var url = $(this).attr('link');
					prew = window.open(url);
				});

                $('.button-delete').button({icons: {primary: "ui-icon-trash"}}).live('click', function(){
                    $( "#dialog-delete:ui-dialog" ).dialog( "destroy" );
					var rowId = $(this).closest('tr').index();
                    var id = $(this).closest('tr').find('td.buyer-id').text();
                    $( "#dialog-delete" ).dialog({
                        resizable: false,
                        draggable: false,
                        height: 140,
                        modal: true,
                        buttons: {
                            "<?php echo $this->translate('Delete this client'); ?>": function() {
                                $.post(
                                    '<?php echo $this->websiteUrl;?>plugin/buyerarea?run=delclient',
                                    {id: id},
                                    function(responce){
                                        if (responce.done) {
											$( "#dialog-delete" ).dialog( 'close' );
											buyersTable.fnDraw();
										} else {
											alert("Can't remove this client");
										}
                                    },
                                    'json'
                                );
                            },
                            "<?php echo $this->translate('Cancel'); ?>": function() {
                                $( this ).dialog( "close" );
                            }
                        }
                    });
                });
				$('#button-settings').button({icons: {primary: "ui-icon-gear"}}).live('click', function(){
					$('#dialog-settings').dialog({
						modal: true,
						width: 500,
						height: 400,
						resizable: false,
						open: function(){
							$(this).load('<?php echo $this->websiteUrl;?>plugin/buyerarea?run=settings');
						},
						buttons: {
							"<?php echo $this->translate('Save settings'); ?>": function(){
								$.post(
									'<?php echo $this->websiteUrl;?>plugin/buyerarea?run=settings'
									,{settings:
											{ email : $(this).find('textarea#email-template').val(),
											  autoemail: $(this).find('#email-autosend').attr('checked') }
									}
									,function(responce){
										if (responce.done){ 
											$('#status-done').show();
										} else {
											$('#status-error').show();
										}
									},
									'json'
								)
							}
						}
					})
				});
				$('#button-import').button({icons: {primary: "ui-icon-circle-arrow-n"}}).live('click', function(){
					$('#dialog-import').dialog({
						modal: true,
						resizable: false,
						draggable: false,
						width: 400,
						open: function(){
							$(this).load('<?php echo $this->websiteUrl;?>plugin/buyerarea?run=uploadForm')
						}
					})
				});
                $('.user-toolbar-button').button("option", "text", false)//.parent().buttonset();
				
				buyersTable = $('#buyerarea_buyers').dataTable({
                    "bJQueryUI": true,
					"bAutoWidth": false,
//                    "bLengthChange": true,
                    "sDom": '<"buyers-table-search"f>rt<"ui-dialog-titlebar ui-widget-header ui-helper-clearfix"lip>',
//                    "bPaginate": true,
//					"sPaginationType": "full_numbers",
					"bScrollInfinite": true,
					"bScrollCollapse": true,
					"sScrollY": "93%",
					"iDisplayLength": 30,
					"bProcessing": true,
					"bServerSide": true,
					"sAjaxSource": "<?php echo $this->websiteUrl;?>plugin/buyerarea?run=clientList",
                    "aoColumnDefs": [
                        { "bSortable": false, "aTargets": [ -1 ] },
                        { "bSearchable": false, "aTargets": [-1, 0, 3] },
                        { "sClass": 'buyer-id', "aTargets": [0] },
                        { "sWidth": '130px', "aTargets": [ -1 ] },
						{ "asSorting": [ "desc" ], "aTargets": [ 5 ] }

//                        { "sWidth": '35px', "aTargets": [ 0 ] },
//                        { "sWidth": '25%', "aTargets": [ 1, 2 ] },
//                        { "sWidth": '20%', "aTargets": [ 3, 4 ] }
                    ],
					"fnServerData": function ( sSource, aoData, fnCallback ) {
						$.ajax( {
							"dataType": 'json',
							"type": "POST",
							"url": sSource,
							"data": aoData,
							"success": fnCallback
						} );
					}
                });

				$('fieldset').delegate('select[name$="country"]', 'change', function(){
					var states = $(this).closest('div').find('select[name$="state"]');
					states.html(loadStates($(this).val()));
					if (!states.html().length){
						states.attr('disabled', true);
					} else {
						states.removeAttr('disabled');
					}
				})

				$('body').delegate(':ui-dialog', 'dialogbeforeclose', function(event, ui){
					$('div.ui-widget-overlay').css({zIndex: 0});
				});
            });

            function loadStates(country) {
                var str = '';

                switch (country) {
                    case 'US':
                        var states = <?php echo json_encode(RCMS_Object_QuickConfig_QuickConfig::$stateListUSA); ?> ;
                        break;
                    case 'CA':
                        var states = <?php echo json_encode(RCMS_Object_QuickConfig_QuickConfig::$stateListCanada); ?> ;
                        break;
                    default:
                        var states = {}
                        break;
                }
                for (var state in states){
                    str += '<option value="'+state+'">'+states[state]+'</option>'
                }
                return str;
            }
        </script>
    </head>
    <body>
        <div id="buyerarea_main" class="ui-dialog" style="padding: 0">
			<div class="ui-dialog-titlebar ui-widget-header ui-helper-clearfix">
				<span class="ui-dialog-title" style="font-size: 20px"><?php echo $this->translate('Manage clients'); ?></span>
				<button class="" id="button-settings" ><?php echo $this->translate('Settings'); ?></button>
				<button class="" id="button-import" ><?php echo $this->translate('Import CSV'); ?></button>
<!--				<a href="<?php echo $this->websiteUrl; ?>plugin/buyerarea?run=manageClients" target="_blank" class="ui-corner-all" role="button"><span class="ui-icon ui-icon-copy">open in new tab</span></a>-->
				<a href="#" onclick="parent.tb_remove();" class="ui-dialog-titlebar-close ui-corner-all" role="button" title="<?php echo $this->translate('close');?>"><span class="ui-icon ui-icon-closethick">close</span></a>
			</div>
            <div id="dialogs-container" style="display: none">
				<div id="dialog-invoice" class="fformated-main" style="float: none !important;">
					<div class="field">
						<label for="invoice_id"><?php echo $this->translate('Invoice id');?>:</label>
						<input type="text" name="invoice_id" id="invoice_id" />
					</div>
					<div class="field">
						<label for="payment_method"><?php echo $this->translate('Payment method');?>:</label>
						<input type="text" name="payment_method" id="payment_method" />
					</div>
					<div class="field">
						<label for="shipping_tax_rate"><?php echo $this->translate('Shipping tax rate');?>, %:</label>
						<input type="text" name="shipping_tax_rate" id="shipping_tax_rate" />
					</div>
				</div>
				<div id="dialog-import" title="<?php echo $this->translate('Import CSV'); ?>">
				</div>
				<div id="dialog-settings" title="<?php echo $this->translate('Settings'); ?>">
				</div>
                <div id="dialog-delete" title="<?php echo $this->translate('Delete client'); ?>">
                    <p class="ui-state-error"><span class="ui-icon ui-icon-alert" style="float:left"></span>
						<?php echo $this->translate('This client will be permanently deleted and cannot be recovered. Are you sure?'); ?>
					</p>
                </div>

                <!--userinfo dialog for admin area-->
                <div id="dialog-userinfo" title="User details">
                    <form action="javascript:;"  name="userinfo" id="userinfo-form">
						<input type="hidden" id="dialog-userinfo-userid" name="userinfo-userid" value=""/>
                        <fieldset title="billing-address" >
                            <div class="ui-widget-header ui-corner-top"><?php echo $this->translate('Billing Address'); ?>:</div>
                            <div class="ui-widget-content ui-corner-bottom">
                                <p><label for="billing-address-firstname"><?php echo $this->translate('Firstname'); ?>:</label><input type="text" name="billing-address-firstname" value="" /></p>
                                <p><label for="billing-address-lastname"><?php echo $this->translate('Lastname'); ?>:</label><input type="text" name="billing-address-lastname" value="" /></p>
                                <p><label for="billing-address-company"><?php echo $this->translate('Company'); ?>:</label><input type="text" name="billing-address-company" value="" /></p>
                                <p><label for="billing-address-email">E-mail:</label><input type="text" name="billing-address-email" value="" /></p>
                                <p><label for="billing-address-phone"><?php echo $this->translate('Phone'); ?>:</label><input type="text" name="billing-address-phone" value="" /></p>
                                <p><label for="billing-address-mobile"><?php echo $this->translate('Mobile'); ?>:</label><input type="text" name="billing-address-mobile" value="" disabled="true"/></p>
                                <p><label for="billing-address-country"><?php echo $this->translate('Country'); ?>:</label>
                                    <?php echo $this->formSelect('billing-address-country', null, null, RCMS_Object_QuickConfig_QuickConfig::$worldCountries); ?>
                                </p>
                                <p><label for="billing-address-city"><?php echo $this->translate('City'); ?>:</label><input type="text" name="billing-address-city" value="" /></p>
                                <p><label for="billing-address-state"><?php echo $this->translate('State'); ?>:</label>
                                    <?php echo $this->formSelect('billing-address-state'); ?></p>
                                <p><label for="billing-address-zip"><?php echo $this->translate('Zip'); ?>:</label><input type="text" name="billing-address-zip" value="" /></p>
                                <p><label for="billing-address-address1"><?php echo $this->translate('Address'); ?>:</label><input type="text" name="billing-address-address1" value="" /></p>
                                <p><label for="billing-address-address2"><?php echo $this->translate('Address').' 2'; ?>:</label><input type="text" name="billing-address-address2" value="" /></p>
                            </div>
                        </fieldset>
                        <fieldset title="shipping-address" >
                            <div class="ui-widget-header ui-corner-top"><?php echo $this->translate('Shipping Address'); ?>:</div>
                            <div class="ui-widget-content ui-corner-bottom">
                                <p><label for="shipping-address-firstname"><?php echo $this->translate('Firstname'); ?>:</label><input type="text" name="shipping-address-firstname" value="" /></p>
                                <p><label for="shipping-address-lastname"><?php echo $this->translate('Lastname'); ?>:</label><input type="text" name="shipping-address-lastname" value="" /></p>
                                <p><label for="shipping-address-company"><?php echo $this->translate('Company'); ?>:</label><input type="text" name="shipping-address-company" value="" /></p>
                                <p><label for="shipping-address-email">E-mail:</label><input type="text" name="shipping-address-email" value="" /></p>
                                <p><label for="shipping-address-phone"><?php echo $this->translate('Phone'); ?>:</label><input type="text" name="shipping-address-phone" value="" /></p>
                                <p><label for="shipping-address-mobile"><?php echo $this->translate('Mobile'); ?>:</label><input type="text" name="shipping-address-mobile" value="" /></p>
                                <p><label for="shipping-address-country"><?php echo $this->translate('Country'); ?>:</label>
                                    <?php echo $this->formSelect('shipping-address-country', null, null, RCMS_Object_QuickConfig_QuickConfig::$worldCountries); ?>
                                </p>
                                <p><label for="shipping-address-city"><?php echo $this->translate('City'); ?>:</label><input type="text" name="shipping-address-city" value="" /></p>
                                <p><label for="shipping-address-state"><?php echo $this->translate('State'); ?>:</label>
                                    <?php echo $this->formSelect('shipping-address-state'); ?></p>
                                <p><label for="shipping-address-zip"><?php echo $this->translate('Zip'); ?>:</label><input type="text" name="shipping-address-zip" value="" /></p>
                                <p><label for="shipping-address-address1"><?php echo $this->translate('Address'); ?>:</label><input type="text" name="shipping-address-address1" value="" /></p>
                                <p><label for="shipping-address-address2"><?php echo $this->translate('Address').' 2'; ?>:</label><input type="text" name="shipping-address-address2" value="" /></p>
                            </div>
                        </fieldset>
                    </form>
					<div style="padding-top: 3px;">
						<table id="dialog-userinfo-history-table">
							<thead>
								<tr>
									<th><?php echo $this->translate('Payment'); ?></th>
									<th><?php echo $this->translate('Date'); ?></th>
									<th><?php echo $this->translate('Details'); ?></th>
									<th></th>
								</tr>
							</thead>
							<tbody>
							</tbody>
						</table>
					</div>
                </div><!--end #dialog-userinfo-->

                <!--user carts dialog-->
                <div id="dialog-usercarts">

                </div><!--end #dialog-usercarts-->

                <!--user quotes dialog-->
                <div id="dialog-userquotes">

                </div><!--end #dialog-userquotes -->

            </div>

            <div id="buyerarea_manageclients" style="position: relative; height: 90%">
                <?php if ($this->buyers) : ?>
                <table class="buyerarea_buyertable" id="buyerarea_buyers">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th><?php echo $this->translate('Client Name'); ?></th>
                            <th>E-mail</th>
                            <th><?php echo $this->translate('Registered'); ?></th>
                            <th><?php echo $this->translate('Last action'); ?></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    
                    </tbody>
                </table>
                <?php else: ?>
                <div class="ui-state-error ui-priority-primary"><span class="ui-icon ui-icon-alert" style="float:left"></span><?php echo $this->translate('No clients yet!'); ?></div>
                <?php endif; ?>
            </div>
        </div>
    </body>
</html>
