<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <div id="buyerarea_main">
            <div id="buyerarea_settings">
                <form>
                    <label for="email-template">E-mail template:</label>
                    <textarea id="email-template"></textarea>
                </form>
            </div>
        </div>
    </body>
</html>
