<style type="text/css">
	#buyerarea_settings ul {
		list-style: none;
}
	#buyerarea_settings ul.ui-widget li {
		display: none
	}
	#buyerarea_settings #email-template-help {
		position: absolute;
		right: 5px;
		top: 5px;
		border: 1px solid #7c7c7c;
		-moz-border-radius: 3px;
		-webkit-border-radius: 3px;
		border-radius: 3px;
	}
	#buyerarea_settings #email-template-help:hover {
		-moz-box-shadow: 0 0 10px #abcdef;
		-webkit-box-shadow: 0 0 10px #abcdef;
		box-shadow: 0 0 10px #abcdef;
	}
	#buyerarea_settings #email-template-help-container {
		position: absolute;
		bottom: 0;
		display: inline;
		padding: 5px;
		border-top: 2px solid #7c7c7c;
		background: #fff;
		width: 100%;
		display: none;
	}

	#buyerarea_settings #email-template-help-container ul {
		
	}
</style>
<div class="buyerarea">
	<div id="buyerarea_settings">
		<ul class="ui-widget">
			<li id="status-done" class="ui-corner-all ui-state-highlight">
				<?php echo $this->translate('Settings updated.'); ?>
			</li>
			<li id="status-error" class="ui-corner-all ui-state-error">
				<?php echo $this->translate('Error. Please, try again.'); ?>
			</li>
		</ul>
		<form>
			<label for="email-template"><?php echo $this->translate('E-mail template'); ?>:</label>
			<div style="position: relative">
				<textarea id="email-template" style="width: 100%; height: 250px; min-height: 100px; padding: 5px"><?php echo $this->settings['email']; ?></textarea>
				<div id="email-template-help" class="ui-state-highlight">
					<span class="ui-icon ui-icon-help" title="help"/>
				</div>
				<div id="email-template-help-container">
					<h3 align="center">You can use following widgets for your template:</h3>
					<ul>
						<li><b>{websiteurl}</b> - Url of your website</li>
						<li><b>{login}</b> - User login</li>
						<li><b>{password}</b> - User password</li>
					</ul>
				</div>
			</div>
				
		</form>
	</div>
</div>
<script type="text/javascript">
	
		$('ul.ui-widget').delegate('li', 'click', function(){
			$(this).hide();
		})

		$('#email-template-help').hover(
		function(){
			$('#email-template-help-container').fadeIn();
		},
		function(){
			$('#email-template-help-container').fadeOut();
		}
		);
	
</script>